name: Ruby

on: ["push"]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Tests (ruby: v${{ matrix.ruby }})
    strategy:
      matrix:
        ruby:
          - '2.7.1'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rubocop -P
      name: Lint Ruby files
  tests:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.1'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec
      name: RSpec
